# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rss_tube/gui/designs\widget_new_feed.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(466, 227)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line_new_feed = QtWidgets.QLineEdit(Dialog)
        self.line_new_feed.setObjectName("line_new_feed")
        self.verticalLayout.addWidget(self.line_new_feed)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.combo_categories = QtWidgets.QComboBox(Dialog)
        self.combo_categories.setObjectName("combo_categories")
        self.verticalLayout.addWidget(self.combo_categories)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.line_name = QtWidgets.QLineEdit(Dialog)
        self.line_name.setObjectName("line_name")
        self.verticalLayout.addWidget(self.line_name)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.cb_receive_notifications = QtWidgets.QCheckBox(Dialog)
        self.cb_receive_notifications.setObjectName("cb_receive_notifications")
        self.verticalLayout.addWidget(self.cb_receive_notifications)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add New Channel"))
        self.label.setText(_translate("Dialog", "New Channel Url:"))
        self.line_new_feed.setPlaceholderText(_translate("Dialog", "https://www.youtube.com/channel/UCq7dxy_qYNEBcHqQVCbc20w"))
        self.label_2.setText(_translate("Dialog", "Category: "))
        self.label_3.setText(_translate("Dialog", "Name:"))
        self.line_name.setPlaceholderText(_translate("Dialog", "(optional)"))
        self.cb_receive_notifications.setText(_translate("Dialog", "Receive Notifications"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
